"""Generates a provenance-grouped report of every open-class Common
word (`examples/common_vocabulary_provenance_report.md`) -- support for
the Point 1 vocabulary-cleanup decision ("we promoted many words to
common, that was incorrect"): which Common words trace back to which
seeding batch, via each Word's own `source_references` (never
re-written after a Word is first created, so this reflects genuine
origin, not a guess).

Read-only: produces a report, changes no data. Every open-class Common
word (closed-class -- determiners, pronouns, etc -- is excluded; those
are unambiguously universal grammar, never in question) falls into
exactly one of five provenance groups:
- LIRA English Metalinguistic Vocabulary v1 -- hand-curated grammar/
  ontology terminology (mood, voice, predicate, entity, place, time,
  cause, being, contribution, interact, ...), never demand-driven.
- LIRA English Definition-Gap Vocabulary v1 -- promoted because the
  Physics Domain's own hydrated definitions referenced them.
- LIRA English Common Definition-Gap Vocabulary v1 -- promoted because
  *Common's own* definitions (many of them words the batch above had
  just added) referenced them -- a second-order cascade, several steps
  removed from Physics specifically.
- LIRA English Morphology Completion v1 -- inflected forms (plurals,
  verb conjugations) of an already-classified lemma; not an independent
  promotion decision of its own.
- LIRA English Common Closed-Class Cache v1 -- a handful of open-class
  words (discourse-marker adverbs, "English" itself) bundled into the
  original closed-class file.

Run: python3 examples/common_vocabulary_provenance_report.py
"""

import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from physics_domain_seeding import run as run_physics_domain  # noqa: E402

OUTPUT_PATH = Path(__file__).resolve().parent / "common_vocabulary_provenance_report.md"
CLOSED_CLASS = {
    "DETERMINER", "PRONOUN", "AUXILIARY", "PREPOSITION", "CONJUNCTION",
    "PARTICLE", "PUNCTUATION", "SYMBOL", "NUMERAL", "INTERJECTION",
}
SAMPLE_STRIDE = 8  # every Nth word, alphabetically -- a spread sample, not cherry-picked


def build_report(dictionary) -> dict:
    by_source = defaultdict(list)
    for word in dictionary.all():
        if not word.is_common or word.part_of_speech.name in CLOSED_CLASS:
            continue
        names = tuple(sorted(ref.source_name.value for ref in word.source_references)) or ("<none>",)
        by_source[names].append((
            word.lexical_form.value if word.lexical_form else word.text,
            word.part_of_speech.name,
            word.definition.value if word.definition else "",
        ))
    for words in by_source.values():
        words.sort()
    return by_source


def render_markdown(by_source: dict) -> str:
    total = sum(len(words) for words in by_source.values())
    lines = [
        "# Common Vocabulary Provenance Report",
        "",
        f"Generated by `examples/common_vocabulary_provenance_report.py`. "
        f"{total} open-class Common words (closed-class grammar excluded), "
        f"grouped by each Word's own `source_references` -- read-only, no data changed.",
        "",
        "## Counts by provenance",
        "",
        "| Source | Count |",
        "|---|---|",
    ]
    ordered = sorted(by_source.items(), key=lambda kv: -len(kv[1]))
    for names, words in ordered:
        lines.append(f"| {names[0]} | {len(words)} |")
    lines.append("")

    for names, words in ordered:
        lines.append(f"## {names[0]} (n={len(words)})")
        lines.append("")
        lines.append("Every word if the group has 40 or fewer; otherwise a spread sample "
                      f"(every {SAMPLE_STRIDE}th word, alphabetically).")
        lines.append("")
        sample = words if len(words) <= 40 else words[::SAMPLE_STRIDE]
        for lexical_form, pos, definition in sample:
            lines.append(f"- **{lexical_form}** ({pos}): {definition}")
        lines.append("")

    return "\n".join(lines) + "\n"


def run() -> dict:
    _, physics_domain = run_physics_domain()
    dictionary = physics_domain.vocabulary.dictionary
    by_source = build_report(dictionary)
    OUTPUT_PATH.write_text(render_markdown(by_source))
    return {"by_source": by_source, "output_path": str(OUTPUT_PATH)}


if __name__ == "__main__":
    result = run()
    print(f"Wrote {result['output_path']}")
    for names, words in sorted(result["by_source"].items(), key=lambda kv: -len(kv[1])):
        print(f"  {len(words):5d}  {names[0]}")
