"""Second Common definition-gap batch: every word referenced inside an
existing Common Vocabulary Cache word's own `definition` text that
wasn't itself seeded (WordSeeder.seed_closed_class_words, i.e. the
mandatory + supplementary + already-promoted vocabulary combined),
found by scanning every seeded word's own Word.definition_words()
against the Dictionary. Distinct from the original 1163-word batch
(common_definition_gap_vocabulary.py) -- this is the gap that remains
after that batch (and everything else since) landed; some of the words
below likely exist only because the *first* batch's own definitions
introduced new gaps of their own (definition-gap closure is not a
single fixed point).

941 words, all Common-only (no Physics component this batch).
Every entry's definition/part_of_speech was authored fresh, one plain
declarative sentence per word, disambiguated where the word's own
referencing definitions gave a clear dominant sense (see
src/lira/vocabulary/assets/common/en/missing_words.json for the full
scan report, including each word's referenced_by_sample).
reference_count is the real number of distinct Common words whose own
definition referenced this word (not a fabricated constant) -- most
entries are well below WordSeeder's promotion_threshold on their own,
so common_definition_gap_vocabulary_seeding_2.py floors it at
promotion_threshold + 1 when actually promoting.

WORD_ENTRIES: lexical_form -> (part_of_speech, definition, reference_count)
"""

WORD_ENTRIES = {
    "abnormal": ("ADJECTIVE", "Not conforming to a standard or expected pattern; unusual or atypical.", 1),
    "absent": ("ADJECTIVE", "Not present; away from a place or not in attendance.", 2),
    "absolutely": ("ADVERB", "Completely or entirely; without doubt, reservation, or qualification.", 1),
    "accent": ("NOUN", "A mark or symbol placed over a letter to indicate pronunciation or stress; a distinctive mode of pronouncing words.", 1),
    "acceptance": ("NOUN", "The action or state of consenting to or approving something willingly.", 1),
    "accidentally": ("ADVERB", "By chance or without intention; unintentionally.", 1),
    "accurate": ("ADJECTIVE", "Conforming precisely to fact or truth; free from error or inaccuracy.", 3),
    "accusation": ("NOUN", "A claim or assertion that someone has done something wrong or illegal.", 1),
    "acknowledge": ("VERB", "To admit the existence, truth, or validity of something; to recognize.", 1),
    "acknowledgement": ("NOUN", "Recognition or thanks given for something; admission of a fact or obligation.", 1),
    "adequate": ("ADJECTIVE", "Satisfactory or sufficient for a particular purpose or need.", 1),
    "adjacent": ("ADJECTIVE", "Situated next to or adjoining something; lying nearby or next door.", 1),
    "adjectivally": ("ADVERB", "In the manner or function of an adjective.", 3),
    "admitting": ("VERB", "Allowing entry or access to; conceding the truth or validity of something.", 1),
    "adverse": ("ADJECTIVE", "Harmful, unfavorable, or opposed; acting against one's interests.", 1),
    "advisable": ("ADJECTIVE", "Recommended as being wise, prudent, or advantageous.", 1),
    "affairs": ("NOUN", "Matters of business, interest, or concern.", 3),
    "ago": ("ADVERB", "At or during a time in the past; previously.", 1),
    "agree": ("VERB", "To have or share the same opinion or view; to consent to something.", 1),
    "agreed": ("VERB", "Settled or arranged by mutual consent or understanding.", 1),
    "agreeing": ("VERB", "Expressing approval or giving consent to something.", 1),
    "airplane": ("NOUN", "A powered aircraft with fixed wings designed for flight through the air.", 1),
    "algebraic": ("ADJECTIVE", "Relating to algebra or involving the use of symbols to represent unknown quantities.", 1),
    "alike": ("ADJECTIVE", "Resembling each other; similar in appearance, nature, or effect.", 1),
    "alluded": ("VERB", "Made an indirect reference to something; suggested without stating directly.", 1),
    "alludes": ("VERB", "Makes an indirect or casual reference to something.", 1),
    "alluding": ("VERB", "Making an indirect reference or suggestion to something.", 1),
    "aloud": ("ADVERB", "Spoken audibly or out loud; not silently.", 2),
    "alphabet": ("NOUN", "A set of letters or characters used to represent the sounds of a language.", 2),
    "amazement": ("NOUN", "A feeling of great surprise or astonishment; wonder.", 1),
    "ambiguity": ("NOUN", "The quality of being open to more than one interpretation or understanding.", 1),
    "analyse": ("VERB", "To examine something in detail to understand its nature, structure, or components.", 1),
    "analysis": ("NOUN", "The process of examining something in detail to understand or explain it.", 1),
    "ancient": ("ADJECTIVE", "Belonging to or existing in times long past; very old.", 1),
    "anger": ("NOUN", "A strong feeling of displeasure, hostility, or resentment.", 1),
    "ankle": ("NOUN", "The joint or area connecting the foot to the leg.", 1),
    "annoy": ("VERB", "To cause minor irritation or displeasure to someone.", 1),
    "appeal": ("NOUN", "A serious or urgent request for something; an application to a higher authority for reconsideration.", 1),
    "application": ("NOUN", "The act or instance of putting something to use; a formal request for consideration.", 1),
    "approximated": ("VERB", "Estimated or calculated as close to a particular value or measurement.", 1),
    "argue": ("VERB", "To present reasons or evidence for or against something; to contend.", 1),
    "argument": ("NOUN", "A set of reasons or facts offered to support a claim; a disagreement or dispute.", 3),
    "arithmetic": ("NOUN", "The branch of mathematics dealing with the operations and properties of numbers.", 1),
    "article": ("NOUN", "A piece of writing or composition; a distinct item or thing.", 1),
    "articles": ("NOUN", "Pieces of writing in a magazine or newspaper; distinct items or things.", 1),
    "articulated": ("ADJECTIVE", "Spoken clearly and distinctly; pronounced with clear articulation.", 2),
    "artistic": ("ADJECTIVE", "Showing creativity, skill, or sensitivity in the creation or appreciation of art.", 1),
    "ash": ("NOUN", "The powdery residue left after something has been burned; a pale gray color.", 1),
    "aside": ("NOUN", "Something said or done in an undertone, in parenthesis, or by the way.", 2),
    "assurance": ("NOUN", "A positive statement or promise intended to give confidence; certainty.", 1),
    "attain": ("VERB", "To succeed in achieving or reaching something; to accomplish.", 1),
    "attainable": ("ADJECTIVE", "Able to be achieved or reached; possible to accomplish.", 1),
    "attentively": ("ADVERB", "In a manner showing careful attention and awareness.", 3),
    "attitude": ("NOUN", "A settled way of thinking or feeling about something; an outlook or disposition.", 1),
    "authorisation": ("NOUN", "Official permission or approval to do something.", 1),
    "authority": ("NOUN", "The power or right to enforce obedience; a person with expert knowledge or commanding position.", 1),
    "aware": ("ADJECTIVE", "Having knowledge or perception of; conscious or cognizant of something.", 9),
    "awareness": ("NOUN", "Knowledge or perception of a situation, fact, or condition.", 2),
    "banknotes": ("NOUN", "Paper money issued by a central or national bank.", 1),
    "barrier": ("NOUN", "A structure or obstacle that prevents or restricts passage or access.", 1),
    "befitting": ("ADJECTIVE", "Being suitable, appropriate, or worthy for someone or something.", 1),
    "behavioural": ("ADJECTIVE", "Relating to the actions, reactions, or conduct of a person or organism.", 1),
    "belief": ("NOUN", "A conviction or acceptance that something is true.", 6),
    "believed": ("VERB", "Accepted as true; held as an opinion or conviction.", 1),
    "best": ("ADJECTIVE", "Of the highest quality, excellence, or merit; most desirable or suitable.", 1),
    "big": ("ADJECTIVE", "Of considerable size, extent, or importance; large.", 1),
    "biological": ("ADJECTIVE", "Relating to living organisms or the processes and phenomena of life.", 1),
    "birth": ("NOUN", "The emergence of a new individual from the body of its parent; the act or process of being born.", 1),
    "black": ("ADJECTIVE", "Of the darkest color, absorbing all light; the absence of visible light wavelengths.", 2),
    "blend": ("VERB", "To mix or combine different elements or substances together.", 1),
    "blending": ("NOUN", "The action or process of mixing two or more things together.", 1),
    "blue": ("NOUN", "A color between green and violet in the spectrum, the color of the sky on a clear day.", 1),
    "bones": ("NOUN", "The hard, rigid structural parts that form the skeleton of vertebrate animals.", 1),
    "books": ("NOUN", "Sets of pages fastened together and bound in covers, containing written or printed material.", 1),
    "bottom": ("NOUN", "The lowest part or surface of something; the base or foundation.", 1),
    "bounding": ("VERB", "To form a boundary or edge around something; to limit or define the extent of.", 1),
    "boys": ("NOUN", "Young male human beings, typically from childhood to adolescence.", 1),
    "bracket": ("NOUN", "A pair of punctuation marks used to enclose and set apart text, such as [] or {}.", 6),
    "brain": ("NOUN", "The organ of the nervous system enclosed in the skull that controls thought, memory, and coordination.", 1),
    "bravery": ("NOUN", "The quality of having courage in the face of danger or difficulty.", 1),
    "break": ("VERB", "To separate into pieces; to interrupt or cease continuity.", 4),
    "breaking": ("NOUN", "The act of causing something to separate into pieces or stop functioning.", 2),
    "breathed": ("VERB", "Drew air into the lungs and expelled it; performed the action of respiration.", 1),
    "briefly": ("ADVERB", "For a short time; in few words; concisely.", 2),
    "broken": ("ADJECTIVE", "Separated into pieces; fractured or no longer whole.", 4),
    "build": ("VERB", "To construct by assembling parts or materials into a completed structure.", 1),
    "building": ("NOUN", "A structure with walls and a roof, such as a house or factory.", 1),
    "bulb": ("NOUN", "A rounded underground plant stem that stores nutrients; or a glass container housing a light filament.", 2),
    "bullet": ("NOUN", "A small projectile fired from a gun; a round marker used in printed lists.", 3),
    "business": ("NOUN", "An enterprise or company engaged in commercial, industrial, or professional activity.", 1),
    "calm": ("ADJECTIVE", "Free from agitation, disturbance, or strong emotion; peaceful.", 3),
    "cannot": ("VERB", "To be unable to; to lack the power or ability to.", 3),
    "capable": ("ADJECTIVE", "Having the power, skill, means, or capacity to do something.", 2),
    "care": ("NOUN", "Serious attention or effort directed toward something; concern or regard for someone's welfare.", 1),
    "careful": ("ADJECTIVE", "Showing close attention to detail; done with caution and diligence.", 3),
    "carriages": ("NOUN", "Vehicles for carrying passengers, especially the wheeled cars of a train.", 1),
    "casual": ("ADJECTIVE", "Not formal or ceremonious; relaxed and informal.", 2),
    "categorise": ("VERB", "To place or arrange into categories or classes; to classify.", 1),
    "categorised": ("VERB", "Placed or arranged into categories or classes; classified.", 1),
    "cease": ("VERB", "To come to an end; to stop or discontinue an activity.", 1),
    "ceasing": ("VERB", "Stopping or ending something.", 2),
    "ceremonious": ("ADJECTIVE", "Marked by formal dignity and established procedures; formal and dignified in manner.", 1),
    "certainly": ("ADVERB", "Without doubt; undoubtedly or definitely.", 1),
    "certainty": ("NOUN", "The state of being sure or certain about something; absolute sureness.", 2),
    "characterised": ("VERB", "Described or distinguished by particular qualities or features.", 1),
    "characterized": ("VERB", "Described or distinguished by particular qualities or features.", 1),
    "check": ("VERB", "To examine or test something to verify its condition or accuracy.", 2),
    "checking": ("VERB", "Examining or testing something to verify its accuracy or condition.", 1),
    "chief": ("ADJECTIVE", "Of greatest importance; principal or main.", 2),
    "chin": ("NOUN", "The part of the face below the mouth, forming the prominence at the front of the lower jaw.", 1),
    "circle": ("NOUN", "A round plane figure bounded by a line of constant distance from its center.", 4),
    "circumference": ("NOUN", "The distance around the perimeter of a circle or circular object.", 1),
    "circumflex": ("NOUN", "A diacritical mark shaped like a small arc or inverted V placed over a letter.", 1),
    "clarifying": ("VERB", "Making something clear, easy to understand, or more distinct.", 1),
    "clever": ("ADJECTIVE", "Quick to understand or learn; skilled or intelligent in a practical way.", 1),
    "cleverly": ("ADVERB", "In a manner showing skill, intelligence, or ingenuity.", 1),
    "closure": ("NOUN", "The act of closing or the condition of being closed; in phonetics, a complete obstruction of the airflow in the mouth.", 1),
    "clouds": ("NOUN", "Visible masses of water droplets or ice crystals suspended in the atmosphere.", 1),
    "coherently": ("ADVERB", "In a manner that is logical, consistent, and easily understood.", 1),
    "coins": ("NOUN", "Pieces of metal, typically round and stamped with official marks, used as money.", 1),
    "cold": ("NOUN", "A low temperature; a condition characterized by absence of heat.", 1),
    "collective": ("ADJECTIVE", "Done by or belonging to people acting together as a group; shared or joint.", 1),
    "collectively": ("ADVERB", "Considered or acted upon as a group or unit rather than individually.", 2),
    "colon": ("NOUN", "A punctuation mark (:) used to introduce a list, explanation, or quotation.", 1),
    "combinations": ("NOUN", "Collections of things joined together or mixed; results of combining elements.", 1),
    "comment": ("NOUN", "A remark or observation expressing an opinion or reaction.", 2),
    "commercial": ("ADJECTIVE", "Relating to trade, business, or the exchange of goods and services for profit.", 1),
    "commitment": ("NOUN", "The state or quality of being dedicated to a person, activity, or cause.", 2),
    "communicate": ("VERB", "To share information or exchange ideas and feelings with others.", 3),
    "communicated": ("VERB", "Imparted or transmitted information, ideas, or meaning.", 2),
    "communicates": ("VERB", "Shares or exchanges information, ideas, or feelings with others.", 1),
    "communities": ("NOUN", "Groups of people living in or occupying the same area or society.", 1),
    "company": ("NOUN", "A commercial business or enterprise; a group of people together.", 1),
    "comparable": ("ADJECTIVE", "Able to be compared; similar enough to be judged in relation to something else.", 1),
    "complied": ("VERB", "Acted in accordance with a rule, request, or demand; obeyed.", 1),
    "comply": ("VERB", "To act in accordance with a rule, request, or demand; to obey.", 1),
    "composition": ("NOUN", "The way in which elements are arranged or combined; a piece of music or written work.", 1),
    "compounds": ("NOUN", "Substances formed by chemically combining two or more elements.", 2),
    "comprehend": ("VERB", "To understand the nature or meaning of something.", 1),
    "comprehending": ("VERB", "Understanding or grasping the meaning of something.", 1),
    "computers": ("NOUN", "Programmable electronic devices that perform calculations and process data.", 2),
    "computing": ("NOUN", "The use of computers or the calculation and processing of numeric values.", 2),
    "conceal": ("VERB", "To hide or keep secret; to prevent from being seen or known.", 2),
    "concentrate": ("VERB", "To focus attention or effort on a particular activity or subject.", 1),
    "concentrating": ("VERB", "Directing attention or effort toward a particular focus or task.", 1),
    "conception": ("NOUN", "An idea or notion; the process of conceiving a child.", 1),
    "concrete": ("ADJECTIVE", "Existing as a specific, tangible, or particular thing rather than in abstract form.", 1),
    "conduct": ("VERB", "To lead, direct, or manage; to behave or act in a particular way.", 4),
    "conducting": ("VERB", "Carrying on or directing an activity, such as leading an orchestra or managing an operation.", 1),
    "conducts": ("VERB", "Directs or manages the course of something; or transmits heat or electricity.", 2),
    "confidence": ("NOUN", "Belief in the reliability, truth, or ability of someone or something.", 2),
    "confident": ("ADJECTIVE", "Feeling or showing certainty about one's abilities or future success.", 1),
    "confidently": ("ADVERB", "With assurance or certainty; showing firm belief or conviction.", 2),
    "confinement": ("NOUN", "The state of being kept within limits; the act of restricting freedom of movement.", 1),
    "confirming": ("VERB", "Establishing the truth or validity of something; affirming or verifying.", 1),
    "conflict": ("NOUN", "Serious disagreement or argument; a state of opposition or incompatibility.", 3),
    "conforming": ("VERB", "Complying with established standards, rules, or patterns.", 1),
    "conformity": ("NOUN", "Compliance with established standards, rules, or patterns; accordance with what is expected.", 1),
    "confront": ("VERB", "To face someone or something in a challenging or opposing manner.", 1),
    "confronting": ("VERB", "Facing someone or something in a challenging or opposing manner; challenging directly.", 1),
    "confusion": ("NOUN", "A state of being unclear in thought or understanding; the act of mixing things up.", 1),
    "connector": ("NOUN", "A device, object, or symbol that joins or links things together; the underscore character (_).", 1),
    "conscious": ("ADJECTIVE", "Aware of one's own thoughts, feelings, and surroundings; mentally alert.", 2),
    "consciousness": ("NOUN", "The state of being aware of one's surroundings, thoughts, and feelings; the mind.", 1),
    "consensus": ("NOUN", "A general agreement or accord among all parties involved.", 1),
    "consider": ("VERB", "To think carefully about something; to regard or deem.", 2),
    "considerable": ("ADJECTIVE", "Worthy of attention; large in amount or importance.", 2),
    "considerably": ("ADVERB", "To a notably large extent; substantially or significantly.", 1),
    "consideration": ("NOUN", "Careful thought about something; a matter worthy of consideration.", 6),
    "consistency": ("NOUN", "The quality of being uniform, regular, or coherent; the degree of thickness or density of a substance.", 1),
    "constantly": ("ADVERB", "Occurring all the time; continuously or repeatedly without interruption.", 1),
    "constriction": ("NOUN", "The action of narrowing or tightening; in phonetics, the reduction of the vocal tract during consonant articulation.", 1),
    "container": ("NOUN", "An object designed to hold, store, or carry something.", 3),
    "continuance": ("NOUN", "The action of continuing something over time; persistence or duration.", 1),
    "contradict": ("VERB", "To deny or assert the opposite of a statement; to be in conflict with something.", 1),
    "contradicting": ("VERB", "Denying or asserting the opposite of a statement; conflicting with something.", 1),
    "contradictory": ("ADJECTIVE", "Mutually opposed or inconsistent; containing or exhibiting contradiction.", 1),
    "contradicts": ("VERB", "Denies or asserts the opposite of a statement; conflicts with something.", 1),
    "convenient": ("ADJECTIVE", "Suitable to someone's needs or circumstances; easy to access or use.", 1),
    "convention": ("NOUN", "A way of behaving or practicing that is widely accepted, traditional, or proper.", 2),
    "conventions": ("NOUN", "Ways of behaving or practicing that are widely accepted, traditional, or proper.", 2),
    "conviction": ("NOUN", "A firm or fixed belief; a declared judgment that someone is guilty.", 1),
    "cooperation": ("NOUN", "Joint action or effort toward a common goal; working together.", 1),
    "copy": ("NOUN", "A reproduction or imitation of an original; a thing to be imitated.", 1),
    "cord": ("NOUN", "A thin rope or string made of twisted strands; a flexible wire or cable.", 1),
    "core": ("NOUN", "The central or most important part of something; the innermost part of a fruit.", 1),
    "correct": ("ADJECTIVE", "Conforming to fact or truth; free from error.", 5),
    "correspondence": ("NOUN", "Communication by exchange of letters; a close similarity or connection between things.", 1),
    "corrosion": ("NOUN", "The gradual destruction of material, especially metal, by chemical reaction with its environment.", 1),
    "cotton": ("NOUN", "A soft, white natural fiber obtained from the seed pods of the cotton plant; cloth or thread made from this fiber.", 1),
    "crash": ("VERB", "To collide with violent force; to move or strike with a loud, shattering sound.", 1),
    "crashing": ("VERB", "Colliding with violent force; moving or striking with a loud, shattering sound.", 1),
    "create": ("VERB", "To bring something into existence; to cause something to come into being.", 1),
    "created": ("VERB", "Caused to come into being; produced or made.", 2),
    "creates": ("VERB", "Brings something into existence; causes something to come into being.", 1),
    "creative": ("ADJECTIVE", "Relating to or involving the use of imagination to produce something new.", 3),
    "creatures": ("NOUN", "Animals or living beings, typically of a particular type or character.", 1),
    "criticise": ("VERB", "To examine or judge something carefully; to express disapproval of someone or something.", 1),
    "crops": ("NOUN", "Plants that are grown and harvested for food or other use; the produce obtained from cultivated plants.", 1),
    "cry": ("NOUN", "A loud or intense utterance of emotion such as pain, fear, or joy.", 1),
    "culture": ("NOUN", "The ideas, customs, and social behavior of a particular society or group of people.", 1),
    "curled": ("VERB", "Formed into a spiral, ring, or coil shape; twisted into a rounded form.", 1),
    "curly": ("ADJECTIVE", "Having curves or spirals; shaped in a curved or twisted form.", 2),
    "currency": ("NOUN", "Money in circulation as a medium of exchange.", 6),
    "customary": ("ADJECTIVE", "According to custom or tradition; habitual or usual.", 2),
    "cut": ("VERB", "To penetrate or separate with or as if with a sharp-edged instrument.", 1),
    "dagger": ("NOUN", "A short pointed blade used as a weapon; or a typographic symbol (†) used in text.", 2),
    "damaged": ("VERB", "Caused or sustained harm or injury to something; impaired or harmed.", 1),
    "danger": ("NOUN", "The possibility or risk of suffering harm or loss; a threat or hazard.", 1),
    "dangerous": ("ADJECTIVE", "Able or likely to cause harm or injury; involving or exposing someone to risk.", 1),
    "dark": ("ADJECTIVE", "Devoid of light; of a deep shade in color; not transparent or translucent.", 1),
    "dash": ("NOUN", "A horizontal line used as punctuation to indicate a break, pause, or connection between words or phrases.", 10),
    "day": ("NOUN", "A period of 24 hours; the period of light between sunrise and sunset.", 1),
    "days": ("NOUN", "Plural of day; periods of 24 hours or periods of daylight.", 1),
    "death": ("NOUN", "The permanent end of all vital functions of a living organism.", 2),
    "debate": ("NOUN", "A formal discussion or argument between opposing sides on a particular topic.", 1),
    "debt": ("NOUN", "Something owed or due to someone else, typically money.", 2),
    "decision": ("NOUN", "A conclusion or resolution reached after deliberation.", 4),
    "decisions": ("NOUN", "Choices or determinations made after consideration or deliberation.", 1),
    "declare": ("VERB", "To state formally or solemnly; to announce officially.", 1),
    "declared": ("VERB", "Stated formally or solemnly; announced officially.", 1),
    "declining": ("VERB", "Politely refusing something; reducing or becoming less in amount or quality.", 1),
    "decorative": ("ADJECTIVE", "Serving to make something more attractive or beautiful; ornamental.", 1),
    "decree": ("NOUN", "An official proclamation or edict issued by an authority.", 1),
    "deep": ("ADJECTIVE", "Extending far down from the surface; profound or intense in quality or feeling.", 1),
    "delay": ("NOUN", "A postponement or deferral; a period of time by which something is late.", 3),
    "deliberately": ("ADVERB", "In a way that is done on purpose or with intent; intentionally.", 3),
    "delicate": ("ADJECTIVE", "Fragile or easily damaged; requiring careful handling or sensitive attention.", 1),
    "demanded": ("VERB", "Made a firm or forceful request for something; required as a necessary condition.", 1),
    "denial": ("NOUN", "A statement that something is not true; refusal to accept or acknowledge something.", 1),
    "denies": ("VERB", "States that something is not true; refuses to accept or grant something.", 1),
    "deny": ("VERB", "To state that something is not true; to refuse to accept or grant something.", 1),
    "denying": ("VERB", "Stating that something is not true; refusing to accept or grant something.", 1),
    "depart": ("VERB", "To leave or go away from a place; to set out on a journey.", 1),
    "departed": ("VERB", "Left or went away from a place; has gone on a journey.", 1),
    "depicted": ("VERB", "Shown or represented in a picture, film, or verbal description.", 1),
    "depicting": ("VERB", "Showing or representing something in a picture, film, or verbal description.", 1),
    "deserve": ("VERB", "To be worthy of or entitled to something by virtue of one's actions or qualities.", 1),
    "designate": ("VERB", "To mark, appoint, or specify for a particular purpose or position.", 1),
    "desirable": ("ADJECTIVE", "Worth wanting or wishing for; attractive or advantageous.", 3),
    "destroy": ("VERB", "To ruin or cause something to cease to exist.", 1),
    "detour": ("NOUN", "A roundabout route taken to avoid the usual direct path.", 1),
    "deviation": ("NOUN", "A departure from an expected course, standard, or norm.", 1),
    "devote": ("VERB", "To give one's time, effort, or attention wholly to a person or cause.", 1),
    "diacritical": ("ADJECTIVE", "Of or relating to a mark used to modify a letter's sound or meaning.", 1),
    "diagram": ("NOUN", "A simplified drawing or representation showing the main features of something.", 2),
    "dialect": ("NOUN", "A regional or social variety of a language.", 1),
    "difficult": ("ADJECTIVE", "Hard to accomplish, face, or deal with; presenting problems or obstacles.", 3),
    "digital": ("ADJECTIVE", "Relating to information represented in digits or electronic format.", 1),
    "dimensions": ("NOUN", "The measurable extents of an object, such as length, width, or height.", 1),
    "directed": ("VERB", "Aimed, pointed, or guided toward a particular target or purpose.", 2),
    "directing": ("VERB", "Guiding or managing the movement or operations of something.", 1),
    "directs": ("VERB", "Points, aims, or guides toward something; manages or controls the action or course of.", 2),
    "disagree": ("VERB", "To have or express a different opinion.", 1),
    "disappointment": ("NOUN", "A feeling of sadness or displeasure caused by unfulfilled hopes.", 1),
    "discomfort": ("NOUN", "A state of mild or moderate physical or mental unease.", 1),
    "disconnected": ("ADJECTIVE", "Not joined together; lacking logical connection.", 1),
    "discussion": ("NOUN", "The exchanging of ideas or opinions on a topic; a conversation or debate.", 2),
    "dismiss": ("VERB", "To reject or cast aside; to end someone's employment.", 1),
    "dismissed": ("VERB", "Rejected or terminated.", 1),
    "disperse": ("VERB", "To scatter or spread out in different directions.", 1),
    "dispute": ("NOUN", "A disagreement or quarrel between parties.", 3),
    "dissent": ("NOUN", "Disagreement with or opposition to an established opinion.", 1),
    "dissimilar": ("ADJECTIVE", "Not alike; showing significant differences.", 1),
    "distress": ("NOUN", "Extreme worry or unhappiness; emotional or physical suffering.", 1),
    "ditto": ("NOUN", "The same as before; a mark indicating a repeated item.", 1),
    "diverse": ("ADJECTIVE", "Composed of many different kinds; showing variety.", 1),
    "double": ("ADJECTIVE", "Consisting of two parts or layers; twice as much.", 4),
    "drag": ("VERB", "To pull something with force along a surface.", 1),
    "drama": ("NOUN", "A work written for stage performance; an intense emotional situation.", 1),
    "durability": ("NOUN", "The ability of something to withstand wear, pressure, or damage; lasting strength.", 2),
    "dutch": ("ADJECTIVE", "Of or relating to the Netherlands, its people, or language.", 1),
    "duties": ("NOUN", "Tasks or responsibilities required in a position or role.", 1),
    "duty": ("NOUN", "A moral or legal obligation; a task that one is expected to perform.", 2),
    "easy": ("ADJECTIVE", "Achieved without difficulty; not hard or demanding.", 4),
    "edges": ("NOUN", "The outer limits or boundaries of something; the sharp or sloping borders of an object.", 2),
    "editing": ("VERB", "The process of revising and preparing text or recorded material for publication.", 1),
    "education": ("NOUN", "The process of teaching and learning in schools or institutions.", 1),
    "effective": ("ADJECTIVE", "Successful in producing the intended result.", 1),
    "eggs": ("NOUN", "Oval reproductive bodies produced by female birds, reptiles, or fish, containing an embryo.", 2),
    "electricity": ("NOUN", "A form of energy resulting from the movement of charged particles.", 4),
    "electronic": ("ADJECTIVE", "Relating to devices that operate using electric current or electrons.", 1),
    "electronically": ("ADVERB", "By electronic means or through electronic devices.", 1),
    "ellipsis": ("NOUN", "A series of dots indicating an omission or pause in text.", 1),
    "emerge": ("VERB", "To come forth from concealment or appear.", 1),
    "emits": ("VERB", "Gives off or sends out light, heat, sound, or energy.", 1),
    "emotional": ("ADJECTIVE", "Relating to, involving, or arising from emotion.", 4),
    "emotionally": ("ADVERB", "In a manner relating to feelings rather than reason.", 1),
    "enables": ("VERB", "Makes something possible; provides the necessary means.", 1),
    "ending": ("NOUN", "The final part or conclusion of something.", 1),
    "energetic": ("ADJECTIVE", "Showing enthusiasm, vigor, and active effort.", 1),
    "engine": ("NOUN", "A machine that produces power or motion.", 1),
    "ensures": ("VERB", "Makes certain; guarantees the occurrence of something.", 1),
    "enter": ("VERB", "To go or come into a place; to begin participation in an activity or arrangement.", 2),
    "entered": ("VERB", "Came or went into; recorded information in.", 1),
    "entirely": ("ADVERB", "Completely or wholly; without exception.", 1),
    "equally": ("ADVERB", "In the same manner or to the same degree.", 1),
    "equilibrium": ("NOUN", "A state of balance in which all forces are counterbalanced.", 1),
    "erect": ("ADJECTIVE", "Upright or vertical in position; standing straight.", 1),
    "estimate": ("VERB", "To form an approximate calculation or judgment of value.", 1),
    "estimated": ("VERB", "Calculated approximately; judged as to value.", 1),
    "estimating": ("VERB", "Forming approximate calculations of value or quantity.", 1),
    "european": ("ADJECTIVE", "Relating to Europe or its peoples, languages, or cultures.", 3),
    "evaluate": ("VERB", "To determine or judge the value or quality of something.", 1),
    "evaluated": ("VERB", "Determined or estimated the value, significance, quality, or merit of something.", 2),
    "evidence": ("NOUN", "Information or facts that serve to prove or support a claim or conclusion.", 8),
    "evoke": ("VERB", "To call forth or bring out a response, memory, or emotion.", 1),
    "evoked": ("VERB", "Called forth; elicited or stirred up.", 1),
    "examination": ("NOUN", "A detailed inspection; a test of knowledge or ability.", 1),
    "exceptional": ("ADJECTIVE", "Unusual; surpassing what is ordinary.", 1),
    "exceptionally": ("ADVERB", "In an unusual or extraordinary manner.", 1),
    "executes": ("VERB", "Carries out or performs an action or instruction.", 1),
    "executing": ("VERB", "Carrying out or performing an action or instruction.", 1),
    "exercise": ("NOUN", "Physical activity undertaken for fitness or health.", 1),
    "expands": ("VERB", "Increases in size, extent, or scope.", 1),
    "expected": ("ADJECTIVE", "Thought likely to happen or occur; regarded as probable or anticipated.", 13),
    "expert": ("NOUN", "A person who has comprehensive and authoritative knowledge in a particular area.", 2),
    "explicit": ("ADJECTIVE", "Stated clearly and in detail; leaving no room for ambiguity or misunderstanding.", 2),
    "extra": ("ADJECTIVE", "Additional to what is usual or expected.", 1),
    "extremities": ("NOUN", "The limbs of the body, especially the hands and feet; the outermost parts or limits.", 2),
    "factory": ("NOUN", "A building or group of buildings where goods are manufactured or assembled.", 2),
    "faculty": ("NOUN", "A power or ability of the mind or body; a department or division of a university.", 3),
    "fairly": ("ADVERB", "In a just or impartial manner; to a moderate degree.", 1),
    "fall": ("VERB", "To move downward under the influence of gravity; to decrease or decline.", 2),
    "falling": ("VERB", "Moving downward or declining in amount.", 1),
    "familiar": ("ADJECTIVE", "Well-known or easily recognized; having knowledge or experience of something.", 2),
    "family": ("NOUN", "A group of related people; a category of related organisms.", 1),
    "fasten": ("VERB", "To secure or attach firmly; to close or make something tight.", 2),
    "fastened": ("ADJECTIVE", "Secured or attached firmly; closed or made tight.", 2),
    "favouring": ("VERB", "Showing preference for or giving advantage to.", 1),
    "fear": ("NOUN", "An unpleasant emotion caused by awareness of danger.", 1),
    "feed": ("VERB", "To give food to; to supply with nourishment.", 1),
    "feeds": ("VERB", "Gives food to; supplies with nourishment.", 1),
    "feel": ("VERB", "To perceive or become aware through the senses; to experience emotion.", 3),
    "felt": ("VERB", "Past tense of feel; perceived or experienced through sensation.", 3),
    "fence": ("NOUN", "A barrier constructed of posts, wire, or boards.", 1),
    "fibre": ("NOUN", "A thin thread-like structure or material; a component of fabric or tissue.", 2),
    "fiction": ("NOUN", "Literature created from imagination rather than fact.", 1),
    "fill": ("VERB", "To make something full; to put a substance into a container until it is full.", 2),
    "filled": ("ADJECTIVE", "Made full; containing or having been provided with something.", 2),
    "final": ("ADJECTIVE", "Coming at or being the end in a sequence, process, or series.", 6),
    "findings": ("NOUN", "Results or conclusions from research or investigation.", 1),
    "fine": ("ADJECTIVE", "Of high quality; thin or delicate in form.", 1),
    "finish": ("VERB", "To bring to an end or completion.", 1),
    "finished": ("VERB", "Brought to completion or conclusion.", 1),
    "finishing": ("NOUN", "The process of completing something or bringing it to final form.", 1),
    "flat": ("ADJECTIVE", "Having a level surface; lacking height or depth.", 1),
    "flawless": ("ADJECTIVE", "Without defects or imperfections; perfect.", 1),
    "flesh": ("NOUN", "The soft tissue covering the bones of an animal body.", 1),
    "flexible": ("ADJECTIVE", "Capable of bending without breaking; able to adapt.", 1),
    "flight": ("NOUN", "The act of flying; a journey by aircraft.", 1),
    "fluently": ("ADVERB", "In a smooth, natural, and effortless manner.", 1),
    "folder": ("NOUN", "A container for holding papers or files; a computer directory.", 1),
    "food": ("NOUN", "Substances consumed for nutrition and energy.", 1),
    "forbidding": ("ADJECTIVE", "Uninviting or threatening in appearance; formidable.", 1),
    "forbids": ("VERB", "Prohibits or refuses to permit.", 1),
    "forcible": ("ADJECTIVE", "Involving or accomplished by physical force; compulsory.", 1),
    "forcibly": ("ADVERB", "By force; using physical coercion or strength.", 1),
    "forehead": ("NOUN", "The part of the face above the eyebrows and below the hairline.", 1),
    "foremost": ("ADJECTIVE", "First in position, order, or importance.", 1),
    "formally": ("ADVERB", "In an official, ceremonial, or proper manner.", 5),
    "forth": ("ADVERB", "Forward in space or time; onward or out.", 3),
    "forward": ("ADVERB", "Toward a place, time, or state ahead; in the direction one is facing or moving.", 9),
    "free": ("ADJECTIVE", "Not under the control of another; at liberty to act or move.", 3),
    "freely": ("ADVERB", "Without restriction, restraint, or constraint; willingly or openly.", 3),
    "frequently": ("ADVERB", "Often; at frequent intervals.", 1),
    "friendly": ("ADJECTIVE", "Kind and pleasant in manner; showing goodwill.", 1),
    "frightens": ("VERB", "Causes fear in; makes afraid.", 1),
    "fulfil": ("VERB", "To bring to completion; to satisfy a requirement.", 1),
    "fulfilled": ("VERB", "Completed the requirements or terms of something; satisfied a desire or need.", 2),
    "fulfilment": ("NOUN", "The action of fulfilling a desire, hope, or promise; the state of being satisfied.", 2),
    "fully": ("ADVERB", "Completely or entirely; to the whole extent.", 5),
    "gain": ("VERB", "To obtain or acquire; to increase or improve in amount or degree.", 3),
    "gained": ("VERB", "Past tense of gain; obtained or acquired.", 3),
    "gaining": ("VERB", "Obtaining, acquiring, or coming to possess something; improving or progressing.", 2),
    "gap": ("NOUN", "An opening or space between things; a break.", 1),
    "gears": ("NOUN", "Toothed wheels that mesh to transmit motion; equipment.", 1),
    "gentle": ("ADJECTIVE", "Mild or soft in manner or effect; kind and tender.", 1),
    "german": ("ADJECTIVE", "Of or relating to Germany, its people, or language.", 1),
    "get": ("VERB", "To obtain, acquire, or receive.", 1),
    "gets": ("VERB", "Obtains or receives.", 1),
    "getting": ("VERB", "Obtaining or receiving.", 1),
    "goal": ("NOUN", "The desired end, object, or result sought to be achieved.", 4),
    "good": ("ADJECTIVE", "Of acceptable or high quality; virtuous or honorable; producing or causing positive results.", 2),
    "goods": ("NOUN", "Items of property or merchandise; physical commodities for sale or transport.", 5),
    "got": ("VERB", "Obtained or received.", 1),
    "government": ("NOUN", "The system by which a community or country is ruled.", 1),
    "gradually": ("ADVERB", "In a slow or gradual manner over a period of time.", 3),
    "grant": ("VERB", "To give, allow, or permit formally.", 1),
    "gravity": ("NOUN", "The force pulling objects toward the earth; seriousness.", 1),
    "greet": ("VERB", "To welcome or acknowledge someone's arrival.", 1),
    "greeted": ("VERB", "Welcomed or acknowledged someone's arrival.", 1),
    "groundwork": ("NOUN", "Preliminary work serving as a foundation for further development.", 1),
    "guidance": ("NOUN", "Advice or information provided to help direct someone.", 1),
    "guide": ("NOUN", "A person or thing that shows the way or provides direction.", 1),
    "guillemet": ("NOUN", "A pair of angled quotation marks used in French and other languages.", 4),
    "habitually": ("ADVERB", "In a customary or regular manner; by habit.", 1),
    "halt": ("VERB", "To stop or come to a complete standstill.", 1),
    "handed": ("VERB", "Gave or delivered something to someone.", 1),
    "happiness": ("NOUN", "The state of being happy; joy or contentment.", 1),
    "harm": ("VERB", "To cause injury, damage, or hurt to someone or something.", 3),
    "harmony": ("NOUN", "A state of agreement or accord; a pleasing combination of different elements.", 2),
    "harsh": ("ADJECTIVE", "Rough, rough or unpleasant to the senses; severe in manner or effect.", 4),
    "heat": ("NOUN", "Energy transferred from one body to another due to temperature difference; warmth.", 2),
    "heaviness": ("NOUN", "The quality of being heavy; weight or burden.", 1),
    "height": ("NOUN", "The measurement of distance from bottom to top; the vertical extent.", 5),
    "helicopter": ("NOUN", "An aircraft with rotating propeller blades enabling vertical flight.", 1),
    "help": ("VERB", "To provide assistance, support, or aid to someone.", 3),
    "helped": ("VERB", "Provided assistance to; made easier.", 1),
    "helps": ("VERB", "Provides assistance; makes easier.", 1),
    "homo": ("NOUN", "The genus that includes human beings and extinct related species.", 2),
    "hopeful": ("ADJECTIVE", "Feeling or expressing hope; showing signs of success.", 1),
    "horizon": ("NOUN", "The line where the earth or sea appears to meet the sky.", 1),
    "horizontal": ("ADJECTIVE", "Parallel to the ground; at right angles to the vertical.", 4),
    "hospitably": ("ADVERB", "In a welcoming and generous manner toward guests.", 1),
    "ideographic": ("ADJECTIVE", "Relating to or using written symbols that represent ideas or objects directly.", 1),
    "illness": ("NOUN", "A disease or condition of being unwell.", 1),
    "illustrate": ("VERB", "To explain or clarify by providing examples, diagrams, or pictures.", 1),
    "illustration": ("NOUN", "A picture or diagram used to explain or clarify text; the act of illustrating.", 1),
    "image": ("NOUN", "A visual representation or picture; a mental impression or conception.", 3),
    "imaginary": ("ADJECTIVE", "Existing in the mind rather than in reality; not real.", 1),
    "imagination": ("NOUN", "The mental faculty of forming ideas and images; creative thinking.", 1),
    "imitation": ("NOUN", "The action of copying someone or something; a copy or reproduction.", 1),
    "impairs": ("VERB", "Weakens or damages; makes worse in quality or function.", 1),
    "imparting": ("VERB", "Giving, conveying, or communicating to someone.", 1),
    "imposed": ("VERB", "Forced or inflicted something unwanted on someone; applied by authority.", 1),
    "impressive": ("ADJECTIVE", "Striking or remarkable in a way that provokes admiration or awe.", 1),
    "improve": ("VERB", "To make or become better in quality, condition, or degree.", 1),
    "inadequate": ("ADJECTIVE", "Insufficient or unsuitable for a particular need or purpose.", 1),
    "indecision": ("NOUN", "The inability or unwillingness to decide; hesitation or vacillation.", 1),
    "independently": ("ADVERB", "In a manner free from external control or dependence.", 1),
    "indispensable": ("ADJECTIVE", "Absolutely essential or necessary.", 1),
    "individuals": ("NOUN", "Separate human beings; distinct persons.", 1),
    "indo": ("ADJECTIVE", "Relating to Indo-European languages and peoples.", 1),
    "ineffective": ("ADJECTIVE", "Not producing the desired or intended result; lacking power or effect.", 2),
    "injury": ("NOUN", "Harm or damage done to the body or to a person's feelings.", 3),
    "innate": ("ADJECTIVE", "Present from birth; inborn or natural.", 1),
    "inner": ("ADJECTIVE", "Located inside; interior or internal.", 1),
    "inquiry": ("NOUN", "An act of seeking information; a formal investigation or examination.", 2),
    "insertion": ("NOUN", "The action of putting something inside something else; the thing inserted.", 1),
    "inspect": ("VERB", "To examine carefully and thoroughly.", 1),
    "instructs": ("VERB", "Teaches or provides instruction to; gives orders or directions to.", 1),
    "intact": ("ADJECTIVE", "Not damaged or broken; whole and complete.", 1),
    "intense": ("ADJECTIVE", "Having great strength, force, or effect; very strong or extreme.", 5),
    "interconnected": ("ADJECTIVE", "Connected together with mutual relationship; linked in a network.", 2),
    "intermediate": ("ADJECTIVE", "Coming between two things in time, position, or degree; middle or median.", 2),
    "internet": ("NOUN", "A global system of interconnected computer networks using standardized protocols for communication.", 2),
    "interpret": ("VERB", "To explain or understand the meaning of something; to translate or construct meaning.", 2),
    "interpreting": ("VERB", "Explaining or revealing the meaning of; translating between languages.", 1),
    "interrobang": ("NOUN", "A punctuation mark combining a question mark and exclamation mark.", 1),
    "interrupted": ("VERB", "Stopped the flow or continuity of; broke in on someone speaking.", 1),
    "interrupting": ("VERB", "Breaking the continuity of; stopping or pausing someone speaking.", 1),
    "intersecting": ("VERB", "Meeting and crossing at a point; having a common area.", 1),
    "introductory": ("ADJECTIVE", "Serving to introduce or provide an introduction; preliminary.", 1),
    "intuition": ("NOUN", "The ability to understand something without conscious reasoning; an immediate insight.", 1),
    "invalid": ("ADJECTIVE", "Not valid; without legal force or effect.", 1),
    "inverted": ("ADJECTIVE", "Turned upside down or reversed in position, order, or direction.", 2),
    "investigated": ("VERB", "Examined or inquired into thoroughly and carefully.", 1),
    "invisible": ("ADJECTIVE", "Unable to be seen; not visible to the eye.", 1),
    "involuntarily": ("ADVERB", "Done without conscious control or will; unintentionally.", 1),
    "irregularly": ("ADVERB", "In a manner that is not regular, consistent, or evenly spaced.", 2),
    "issue": ("NOUN", "A topic of concern or debate; a problem or difficulty.", 1),
    "iteration": ("NOUN", "A new version or instance of something; a repetition of a process.", 1),
    "japan": ("NOUN", "A country in East Asia consisting of four main islands in the Pacific Ocean.", 2),
    "job": ("NOUN", "A task or piece of work; a paid position of employment.", 1),
    "jointed": ("ADJECTIVE", "Having joints; composed of segments connected by joints.", 1),
    "jointly": ("ADVERB", "Together with another or others; in partnership or cooperation.", 2),
    "journey": ("NOUN", "A long or relatively long distance traveled from one place to another.", 2),
    "judgement": ("NOUN", "The ability to make sound decisions; a formal court decision or verdict.", 1),
    "judgements": ("NOUN", "Plural of judgement; decisions or verdicts.", 1),
    "justified": ("ADJECTIVE", "Having a good or valid reason; shown to be right or proper.", 1),
    "kindness": ("NOUN", "The quality of being kind; considerate and helpful behavior.", 1),
    "king": ("NOUN", "A male sovereign ruler of a kingdom.", 1),
    "kingdom": ("NOUN", "A realm or territory ruled by a monarch; one of the major divisions of living organisms.", 2),
    "land": ("NOUN", "The solid part of the earth's surface not covered by water; ground or earth.", 2),
    "largest": ("ADJECTIVE", "Greatest in size, extent, or degree; superlative of large.", 1),
    "last": ("VERB", "To continue in existence or use; to endure for a period of time.", 1),
    "lasting": ("ADJECTIVE", "Enduring or continuing for a long time; not temporary or fleeting.", 3),
    "latest": ("ADJECTIVE", "Most recent or newest; happening at the end of a series.", 1),
    "law": ("NOUN", "A rule or regulation established and enforced by authority.", 4),
    "layer": ("NOUN", "A sheet or thickness of material; a level or stratum.", 1),
    "learned": ("VERB", "Acquired knowledge or skill through study or experience.", 1),
    "leg": ("NOUN", "A limb of an animal used for walking or supporting the body.", 1),
    "legal": ("ADJECTIVE", "Permitted, authorized, or established by law.", 6),
    "legs": ("NOUN", "Plural of leg; limbs of an animal used for movement.", 1),
    "let": ("VERB", "To allow or permit; to enable or cause.", 1),
    "lets": ("VERB", "Allows or permits; enables to happen.", 1),
    "liable": ("ADJECTIVE", "Legally responsible or answerable; likely or subject to.", 1),
    "life": ("NOUN", "The state or fact of being alive; the period from birth to death.", 1),
    "light": ("NOUN", "Visible electromagnetic radiation that enables sight.", 5),
    "liking": ("NOUN", "A preference or affection for someone or something; a favorable disposition.", 2),
    "limbs": ("NOUN", "Arms or legs; body parts used for movement.", 1),
    "listed": ("VERB", "Included in a list; recorded or registered.", 1),
    "live": ("VERB", "To have life; to remain alive or to dwell in a place.", 3),
    "lives": ("VERB", "Resides or makes one's home in a place; experiences or passes time in a particular way.", 2),
    "living": ("ADJECTIVE", "Having life; alive or currently existing.", 5),
    "locomotive": ("NOUN", "A powered rail vehicle for pulling trains.", 1),
    "logic": ("NOUN", "The systematic use of reason and evidence to determine truth, validity, or the right course of action.", 2),
    "loss": ("NOUN", "The state of being deprived of something; bereavement, deprivation, or absence.", 2),
    "love": ("NOUN", "An intense feeling of affection and care for another person or thing.", 1),
    "loyalty": ("NOUN", "Faithfulness or allegiance to a person, group, cause, or ideal.", 1),
    "lying": ("VERB", "Resting horizontally; positioned or situated in a particular place.", 2),
    "magnet": ("NOUN", "An object that produces a magnetic field and attracts certain metals.", 1),
    "mainly": ("ADVERB", "Chiefly or principally; for the most part.", 1),
    "manage": ("VERB", "To be in charge of or direct; to handle or cope with.", 1),
    "manifold": ("ADJECTIVE", "Numerous and various; many and of different kinds.", 1),
    "manually": ("ADVERB", "By hand rather than by machine; done without automation.", 1),
    "markedly": ("ADVERB", "In a noticeable or conspicuous manner; strikingly.", 1),
    "mass": ("NOUN", "A large quantity of material or substance; a significant amount or scale; or the amount of matter in an object.", 2),
    "match": ("VERB", "To be equal or corresponding to; to resemble or correspond with.", 1),
    "mathematics": ("NOUN", "The study of numbers, quantities, shapes, and their relationships and operations.", 3),
    "maturity": ("NOUN", "The state of being fully developed or mature; full growth.", 1),
    "mechanism": ("NOUN", "A device, process, or system of working parts; the way something operates or functions.", 2),
    "meet": ("VERB", "To encounter or come into contact with; to satisfy a need or requirement.", 3),
    "meeting": ("NOUN", "An assembly or gathering of people for a specific purpose; an encounter or convergence.", 2),
    "meets": ("VERB", "Encounters or comes into contact with; satisfies or fulfills.", 1),
    "men": ("NOUN", "Adult male human beings; plural of man.", 1),
    "mend": ("VERB", "To repair or restore something that is broken or torn.", 1),
    "mentally": ("ADVERB", "In a way relating to the mind; psychologically or intellectually.", 1),
    "merging": ("VERB", "Combining or blending into one; uniting or joining together.", 1),
    "messages": ("NOUN", "Plural of message; communications or information conveyed.", 1),
    "met": ("VERB", "Past tense of meet; encountered or satisfied.", 3),
    "metal": ("NOUN", "A hard, typically shiny substance that is a good conductor of heat and electricity.", 4),
    "metals": ("NOUN", "Solid materials that typically conduct electricity and heat.", 1),
    "mille": ("NOUN", "A unit equal to one thousandth; one per thousand.", 1),
    "minor": ("ADJECTIVE", "Small in degree, significance, or importance; lesser or subordinate.", 2),
    "modifier": ("NOUN", "A word, phrase, or mark used to change, limit, or qualify the meaning of another word or expression.", 2),
    "monetary": ("ADJECTIVE", "Relating to money or currency.", 4),
    "month": ("NOUN", "A division of a year; one of the twelve periods into which the calendar year is divided.", 2),
    "moral": ("ADJECTIVE", "Relating to principles of right and wrong behavior; ethical.", 1),
    "morality": ("NOUN", "Principles concerning the distinction between right and wrong behavior.", 1),
    "mostly": ("ADVERB", "On the whole; for the most part; usually.", 1),
    "motion": ("NOUN", "The act or process of moving; a formal proposal in a meeting.", 1),
    "movements": ("NOUN", "Acts of moving or changing position; organized activities or campaigns.", 1),
    "music": ("NOUN", "Vocal or instrumental sounds organized into patterns to produce beauty of form and expression.", 1),
    "nation": ("NOUN", "A large group of people united by common descent, culture, language, or government.", 1),
    "nearest": ("ADJECTIVE", "Closest in distance; superlative of near.", 1),
    "nearly": ("ADVERB", "Almost; at or to within a short distance or time.", 1),
    "nearness": ("NOUN", "The quality or state of being near; proximity.", 1),
    "necessarily": ("ADVERB", "In a way that is unavoidable or required; as a logical consequence or inevitability.", 2),
    "negotiated": ("VERB", "Discussed terms and reached agreement with another party; maneuvered carefully.", 1),
    "net": ("NOUN", "A mesh of cord or rope used for catching things; an open-meshed fabric.", 1),
    "neutral": ("ADJECTIVE", "Not supporting either side in a conflict; impartial or unbiased.", 1),
    "non": ("ADJECTIVE", "Indicating the absence or negation of something.", 5),
    "nonmetallic": ("ADJECTIVE", "Lacking the properties of a metal; not metallic in nature.", 1),
    "north": ("NOUN", "One of the four cardinal directions; the direction toward the North Pole.", 1),
    "nose": ("NOUN", "The facial feature used for smelling and breathing.", 1),
    "notably": ("ADVERB", "In a notable or remarkable manner; particularly or especially.", 1),
    "notation": ("NOUN", "A system of signs or symbols representing something; the act of making notes.", 1),
    "note": ("NOUN", "A brief written record or message; a footnote or annotation.", 1),
    "noteworthy": ("ADJECTIVE", "Worthy of notice or attention; remarkable or significant.", 2),
    "noticeable": ("ADJECTIVE", "Able to be noticed; visible or obvious; perceptible.", 1),
    "noticeably": ("ADVERB", "In a way that is noticeable; perceptibly or clearly.", 1),
    "noting": ("VERB", "Observing or perceiving; writing or recording briefly.", 1),
    "nullify": ("VERB", "To make null or void; to invalidate or cancel.", 1),
    "numeral": ("NOUN", "A figure or symbol used to represent a number.", 3),
    "obstacle": ("NOUN", "Something that impedes or obstructs progress; a difficulty or hindrance.", 1),
    "obvious": ("ADJECTIVE", "Clearly visible or apparent; easily understood; not needing explanation.", 1),
    "occupation": ("NOUN", "A job or profession; the action or state of occupying.", 1),
    "offend": ("VERB", "To cause displeasure or resentment; to violate or transgress a rule.", 1),
    "offered": ("VERB", "Presented or made available for acceptance; proposed or suggested.", 2),
    "office": ("NOUN", "A room or building where administrative or professional work is done; a position of responsibility.", 1),
    "official": ("ADJECTIVE", "Authorized by or proceeding from a person or organization with authority.", 9),
    "officially": ("ADVERB", "In an official, formal, or authorized manner.", 3),
    "offspring": ("NOUN", "The young of an animal or plant; a person's child or children.", 1),
    "old": ("ADJECTIVE", "Having existed for a long time; former or previous.", 1),
    "open": ("ADJECTIVE", "Not closed or blocked; allowing passage or access.", 6),
    "opening": ("NOUN", "A gap or aperture; the action of opening; an available position.", 1),
    "opinion": ("NOUN", "A belief or judgment held with confidence but not necessarily proven by fact.", 9),
    "opinions": ("NOUN", "Beliefs or judgments not necessarily based on fact; plural of opinion.", 1),
    "opportunity": ("NOUN", "A favorable chance or occasion; a convenient time to do something.", 1),
    "orderly": ("ADJECTIVE", "Arranged or proceeding in a systematic and peaceful manner.", 1),
    "organ": ("NOUN", "A part of an organism with a specific function; a musical instrument with pipes.", 1),
    "organic": ("ADJECTIVE", "Relating to or produced by living organisms; containing carbon.", 3),
    "organisation": ("NOUN", "An organized group of people with a common purpose; the act of organizing.", 1),
    "organise": ("VERB", "To arrange or put in order; to establish or prepare something systematically.", 2),
    "organised": ("ADJECTIVE", "Arranged in a systematic manner; well-structured or planned.", 1),
    "organism": ("NOUN", "A living individual, such as an animal or plant; a living system.", 1),
    "organisms": ("NOUN", "Plural of organism; living individuals or systems.", 1),
    "organization": ("NOUN", "A group of people with a shared purpose; the arrangement or structure of something.", 3),
    "organizations": ("NOUN", "Plural of organization; structured groups or systems.", 1),
    "organize": ("VERB", "To arrange or put in order; to form or establish in a structured way.", 1),
    "organized": ("ADJECTIVE", "Arranged in a methodical way; put in order or systematically arranged.", 2),
    "organs": ("NOUN", "Parts of a body that perform specific functions.", 3),
    "oriented": ("ADJECTIVE", "Positioned or aligned in a particular direction or relative to a reference point.", 1),
    "outer": ("ADJECTIVE", "Located on the outside or external surface of something.", 1),
    "outright": ("ADJECTIVE", "Complete or total, without qualification or hesitation.", 1),
    "overcome": ("VERB", "To defeat or deal successfully with a problem or difficulty.", 1),
    "overlapping": ("ADJECTIVE", "Extending over and covering part of something else.", 1),
    "owed": ("VERB", "Was under a financial or moral obligation to pay or repay something.", 2),
    "owned": ("VERB", "Had legal possession or title to something; possessed.", 2),
    "owning": ("VERB", "Acknowledging or admitting something; or possessing something as owner.", 2),
    "page": ("NOUN", "A sheet of paper, or one side of a sheet in a book or document.", 1),
    "paid": ("VERB", "Past tense of pay; gave money in exchange for goods or services.", 5),
    "pair": ("NOUN", "Two things of the same kind used together.", 1),
    "paper": ("NOUN", "A thin sheet material made from cellulose pulp; a document or written piece.", 2),
    "papers": ("NOUN", "Sheets of paper, or documents and written records.", 1),
    "parenthesis": ("NOUN", "Either of a pair of curved brackets used to enclose text; the enclosed text itself.", 2),
    "partial": ("ADJECTIVE", "Relating to or affecting only part of something; incomplete.", 1),
    "participant": ("NOUN", "A person who takes part in an activity or event.", 1),
    "participate": ("VERB", "To take part in or become involved in an activity or event.", 2),
    "particulars": ("NOUN", "Individual facts, details, or specific pieces of information.", 1),
    "pasture": ("NOUN", "Land covered with grass used for grazing animals.", 1),
    "pause": ("NOUN", "A temporary stop or break; a silence or hesitation in speech or action.", 2),
    "pay": ("VERB", "To give money in exchange for goods, services, or debts.", 1),
    "pen": ("NOUN", "An instrument for writing or drawing with ink.", 1),
    "perceptible": ("ADJECTIVE", "Able to be noticed or detected by the senses.", 1),
    "perception": ("NOUN", "The way in which something is understood or interpreted.", 1),
    "permanent": ("ADJECTIVE", "Lasting or intended to last indefinitely; not temporary.", 3),
    "persisting": ("VERB", "Continuing to exist or occur despite opposition or difficulty.", 1),
    "photographic": ("ADJECTIVE", "Relating to photography, or accurate and detailed like a photograph.", 1),
    "physiological": ("ADJECTIVE", "Relating to the normal functions and processes of living organisms.", 1),
    "pick": ("VERB", "To choose or select something from a number of options.", 1),
    "picks": ("NOUN", "Selected items or choices; also tools for breaking up hard surfaces.", 1),
    "picture": ("NOUN", "A visual representation of something created by painting, drawing, or photography.", 1),
    "pilcrow": ("NOUN", "The symbol ¶ used to mark the beginning of a new paragraph.", 1),
    "placing": ("VERB", "Putting something in a particular position or location.", 1),
    "planet": ("NOUN", "A large spherical celestial body that orbits a star.", 1),
    "planned": ("VERB", "Arranged or prepared in advance; intended or expected to happen.", 2),
    "plants": ("NOUN", "Living organisms that produce their own food through photosynthesis; factories or installations.", 2),
    "pleasure": ("NOUN", "A feeling of happiness, contentment, or satisfaction; something that gives enjoyment.", 2),
    "poetry": ("NOUN", "Literary work composed in verse, typically expressing emotion or narrative.", 1),
    "policy": ("NOUN", "A course or principle of action adopted or proposed by a government or organization.", 1),
    "politely": ("ADVERB", "In a courteous, well-mannered, or respectful way.", 2),
    "powered": ("ADJECTIVE", "Supplied with or operated by mechanical or electrical energy.", 1),
    "powerful": ("ADJECTIVE", "Having great strength, energy, or effect; capable of producing strong impact or influence.", 2),
    "practice": ("NOUN", "The actual application of a skill; repeated performance to develop proficiency.", 3),
    "precise": ("ADJECTIVE", "Exact and accurate in detail; marked by exactness and accuracy.", 7),
    "prediction": ("NOUN", "A statement about what will happen in the future.", 1),
    "preferred": ("ADJECTIVE", "Liked or chosen in preference to alternatives.", 1),
    "preparation": ("NOUN", "The process of making something ready or the thing made ready.", 1),
    "prepared": ("ADJECTIVE", "Made ready or fit for a particular purpose.", 1),
    "preparing": ("VERB", "Making something ready for use or for a future event.", 1),
    "prepositionally": ("ADVERB", "In the manner of or by means of a preposition.", 1),
    "presented": ("VERB", "Past tense of present; offered, given, or introduced.", 4),
    "presenting": ("VERB", "Showing or introducing something to an audience or person.", 1),
    "presents": ("NOUN", "Gifts given to someone, or instances of showing or introducing.", 1),
    "pressure": ("NOUN", "The continuous physical force exerted on or against a surface.", 1),
    "price": ("NOUN", "The amount of money required to purchase something.", 1),
    "prime": ("NOUN", "A symbol (') denoting a derivative, variation, or first occurrence; or the most important or first position.", 2),
    "principal": ("ADJECTIVE", "First in order, rank, or importance; chief or primary.", 2),
    "principle": ("NOUN", "A fundamental truth or proposition serving as the basis for a system or theory.", 1),
    "principles": ("NOUN", "Fundamental rules or accepted theories guiding conduct or operation.", 3),
    "printed": ("ADJECTIVE", "Produced on paper by ink, type, or other means.", 4),
    "printing": ("NOUN", "The process of reproducing text and images on paper or other surfaces; printed material.", 2),
    "prints": ("NOUN", "Reproductions of images or photographs; also marks or impressions.", 1),
    "prize": ("NOUN", "Something of value awarded as a reward for winning a competition.", 1),
    "probable": ("ADJECTIVE", "Likely to happen, be true, or be the case; having a reasonable chance of occurring.", 2),
    "proceed": ("VERB", "To go forward or continue with an action or movement.", 1),
    "proceeding": ("NOUN", "A course of action or series of actions taken; a legal action or lawsuit.", 2),
    "professional": ("ADJECTIVE", "Relating to or characteristic of a profession or skilled occupation.", 1),
    "progress": ("NOUN", "Forward movement or advancement; improvement toward a goal.", 6),
    "prominence": ("NOUN", "The quality of standing out or being noticeable; distinction or importance.", 3),
    "promise": ("NOUN", "A declaration assuring that one will or will not do something; grounds for hope or expectation.", 2),
    "promised": ("VERB", "Made a commitment or pledge that something would be done.", 1),
    "promises": ("NOUN", "Commitments or pledges to do or provide something.", 1),
    "promoting": ("VERB", "Advancing someone or something to a higher position or publicizing it.", 1),
    "proof": ("NOUN", "Evidence or documentation that demonstrates the truth or validity of something.", 4),
    "properly": ("ADVERB", "In a correct, appropriate, or fitting manner.", 1),
    "proposal": ("NOUN", "A plan or suggestion put forward for consideration.", 1),
    "proposed": ("VERB", "Suggested or put forward an idea or plan for consideration.", 1),
    "propositions": ("NOUN", "Statements or assertions to be proved or discussed.", 1),
    "proven": ("ADJECTIVE", "Shown to be true or genuine by evidence or testing.", 2),
    "prudent": ("ADJECTIVE", "Acting with care and good judgment to avoid unnecessary risk.", 1),
    "public": ("ADJECTIVE", "Relating to or accessible to the people in general.", 1),
    "publication": ("NOUN", "The act or business of producing and making something available to the public.", 2),
    "publicly": ("ADVERB", "In a manner known to, done in front of, or accessible to the general public.", 2),
    "publish": ("VERB", "To make information available to the public through print or other media.", 1),
    "punctuation": ("NOUN", "Marks used in written text to organize meaning and clarify structure, such as periods, commas, and question marks.", 60),
    "pursuit": ("NOUN", "An activity or interest that someone engages in or chases after.", 1),
    "queen": ("NOUN", "A female monarch or the wife of a king.", 1),
    "quick": ("ADJECTIVE", "Lasting or taking only a short time; swift.", 2),
    "quiet": ("ADJECTIVE", "Free from noise or disturbance; silent or calm.", 1),
    "quotation": ("NOUN", "A passage or phrase taken from a text and repeated by another.", 1),
    "quote": ("NOUN", "A pair of punctuation marks used to enclose and set apart quoted text.", 12),
    "radio": ("NOUN", "A device for receiving transmitted sound signals through electromagnetic waves.", 1),
    "railway": ("NOUN", "A system of tracks laid for trains to run on.", 1),
    "raising": ("VERB", "Lifting something upward or increasing its level or amount.", 1),
    "ranked": ("VERB", "Arranged in a series or order according to some standard.", 1),
    "rapid": ("ADJECTIVE", "Happening or occurring with great speed; swift.", 2),
    "reaction": ("NOUN", "A response to something; an action prompted by a stimulus.", 4),
    "reactions": ("NOUN", "Responses or replies to something experienced or encountered.", 1),
    "reality": ("NOUN", "The state of things as they actually exist; what is real or actual.", 3),
    "reasonable": ("ADJECTIVE", "Fair or justified based on sound judgment and rational thought.", 1),
    "reasonably": ("ADVERB", "In a manner that is fair, rational, or sensible.", 1),
    "recently": ("ADVERB", "Not long ago in the immediate past.", 1),
    "recognized": ("VERB", "Identified, perceived, or acknowledged as having a specified nature or significance.", 2),
    "recognizing": ("VERB", "Identifying or acknowledging the presence or identity of something.", 1),
    "recommendations": ("NOUN", "Suggestions or advice put forward as worthy of acceptance.", 1),
    "record": ("NOUN", "A written account or documentation of something; a stored account of facts.", 3),
    "recorded": ("VERB", "Past tense of record; set down in writing or other permanent form.", 3),
    "records": ("NOUN", "Documents, files, or information about past events or transactions.", 1),
    "recover": ("VERB", "To return to a normal state of health, strength, or operation.", 2),
    "recurring": ("ADJECTIVE", "Happening or appearing repeatedly at intervals.", 1),
    "reduced": ("VERB", "Past tense of reduce; made smaller or less in size, amount, or degree.", 3),
    "reflects": ("VERB", "Bounces back light or an image; also means to consider or think deeply.", 1),
    "reform": ("NOUN", "Change or improvement intended to correct faults or abuses.", 1),
    "refrain": ("VERB", "To hold back or abstain from doing something.", 1),
    "refuse": ("VERB", "To decline or reject an offer or request.", 1),
    "regional": ("ADJECTIVE", "Relating to or characteristic of a particular geographic area.", 1),
    "regular": ("ADJECTIVE", "Occurring or happening uniformly or at fixed intervals; following an established pattern.", 2),
    "reigning": ("VERB", "Currently holding the position of monarch or champion.", 1),
    "relax": ("VERB", "To become less tense or rigid; to rest and ease tension.", 2),
    "relaxed": ("ADJECTIVE", "Free from tension or formality; calm and at ease.", 1),
    "relevant": ("ADJECTIVE", "Closely connected or appropriate to the matter at hand.", 4),
    "reliability": ("NOUN", "The quality of being consistent, dependable, and worthy of trust.", 2),
    "reliable": ("ADJECTIVE", "Able to be trusted to do what is needed or expected.", 1),
    "reluctance": ("NOUN", "Unwillingness or hesitation to do something.", 1),
    "remain": ("VERB", "To stay or continue in the same place, position, or state.", 2),
    "remains": ("VERB", "To stay or continue in a certain state or position.", 3),
    "remarkable": ("ADJECTIVE", "Worthy of attention or striking in a noticeable way.", 1),
    "remember": ("VERB", "To recall or bring back into the mind from memory.", 1),
    "repair": ("VERB", "To restore something to working order after damage or wear.", 1),
    "repeatedly": ("ADVERB", "Done or said many times; over and over.", 3),
    "repentance": ("NOUN", "Feeling or expressing regret and asking for forgiveness for wrongdoing.", 1),
    "reproduce": ("VERB", "To create a copy or representation of something; also to generate offspring.", 1),
    "resemble": ("VERB", "To be similar to something in appearance, qualities, or characteristics.", 2),
    "resembling": ("VERB", "Having qualities similar to; looking or being like something else.", 3),
    "resistance": ("NOUN", "The action of opposing or withstanding something; the opposition to electric current flow in a conductor.", 2),
    "resolute": ("ADJECTIVE", "Admirably purposeful, determined, and unwavering.", 1),
    "resources": ("NOUN", "Supplies, assets, materials, or capabilities available for use when needed.", 2),
    "responsibility": ("NOUN", "The state of being accountable for one's actions; a duty or obligation.", 1),
    "restraint": ("NOUN", "The action of holding back or limiting something.", 1),
    "reversed": ("ADJECTIVE", "Turned backward or inverted in position or order.", 1),
    "rigid": ("ADJECTIVE", "Stiff and unable to bend; unyielding or inflexible.", 1),
    "rise": ("VERB", "To move upward or to increase in level or amount.", 1),
    "rising": ("ADJECTIVE", "Moving or increasing upward in level or amount.", 1),
    "rod": ("NOUN", "A thin straight stick or bar of wood, metal, or other material.", 1),
    "rotates": ("VERB", "Turns around a central point or axis.", 1),
    "rough": ("ADJECTIVE", "Having an uneven or irregular surface; not smooth.", 1),
    "ruling": ("NOUN", "A decision or determination made by a court or official authority.", 1),
    "run": ("VERB", "To move quickly with rapid steps; also to operate or manage.", 1),
    "sadness": ("NOUN", "The state of being sad; sorrow or melancholy.", 1),
    "safe": ("ADJECTIVE", "Free from danger, risk, or the likelihood of causing harm.", 2),
    "sapiens": ("NOUN", "The human species; used in biological classification as part of the binomial name Homo sapiens.", 2),
    "satisfactory": ("ADJECTIVE", "Acceptable and meeting the required standard; adequate.", 2),
    "scandinavian": ("ADJECTIVE", "Relating to Scandinavia or its peoples, languages, or cultures.", 1),
    "scheduled": ("ADJECTIVE", "Arranged or planned to occur at a specific time.", 1),
    "scheme": ("NOUN", "A systematic plan or arrangement of related things.", 1),
    "scoring": ("VERB", "Earning or recording points in a game or competition.", 1),
    "sea": ("NOUN", "A large body of salt water connected to or part of an ocean.", 1),
    "searching": ("VERB", "Looking carefully for something or someone.", 1),
    "seat": ("NOUN", "A place of residence, authority, or jurisdiction; the central location of something abstract.", 2),
    "secure": ("ADJECTIVE", "Free from danger or risk; safe.", 1),
    "securely": ("ADVERB", "In a manner that is firmly fixed or protected; safely.", 2),
    "seeking": ("VERB", "Attempting to find or obtain something.", 1),
    "seize": ("VERB", "To take hold of something suddenly or forcibly.", 1),
    "seizing": ("VERB", "Taking hold of something suddenly or forcibly.", 1),
    "self": ("NOUN", "A person's own individual identity, essence, or being.", 2),
    "semi": ("ADJECTIVE", "Partially or partly; approximately half.", 3),
    "sending": ("VERB", "Causing something to go or move in a particular direction.", 1),
    "sensations": ("NOUN", "Physical perceptions or feelings arising from stimulation of the bodily senses.", 2),
    "sensible": ("ADJECTIVE", "Showing or having good practical judgment; reasonable.", 1),
    "sent": ("VERB", "Caused to go or be transmitted to a destination; dispatched.", 2),
    "serious": ("ADJECTIVE", "Grave in manner or character; not joking or light-hearted.", 1),
    "service": ("NOUN", "Work performed or duties done for another person or organization.", 1),
    "services": ("NOUN", "Work performed or duties done for others; also professional occupations.", 1),
    "severe": ("ADJECTIVE", "Serious, extreme, or harsh in nature or effect.", 5),
    "sewing": ("NOUN", "The act or process of joining fabric or other materials together using thread and a needle.", 2),
    "sex": ("NOUN", "Either of the two main biological divisions of organisms based on reproductive characteristics.", 4),
    "sharp": ("ADJECTIVE", "Having a fine or keen edge; also marked by abrupt change in direction.", 1),
    "shoulder": ("NOUN", "The part of the body where the arm joins the trunk.", 1),
    "shut": ("VERB", "To move or close something into a position that blocks an opening.", 2),
    "signifies": ("VERB", "To be an indication or sign of; to communicate a meaning.", 2),
    "signify": ("VERB", "To indicate or point out; to have significance or meaning.", 1),
    "signifying": ("VERB", "Acting as a sign or indication of; meaning or denoting.", 2),
    "simpler": ("ADJECTIVE", "Less complex or involved than something else.", 1),
    "simplified": ("ADJECTIVE", "Reduced to a simpler or more basic form; made less complex.", 2),
    "situated": ("ADJECTIVE", "Located in or placed at a particular position or place.", 4),
    "skilfully": ("ADVERB", "In a manner showing trained ability and competence.", 1),
    "skillfully": ("ADVERB", "In a manner showing trained ability and competence.", 1),
    "slender": ("ADJECTIVE", "Long and thin; having little thickness or width in proportion to length.", 2),
    "slight": ("ADJECTIVE", "Small in degree or amount; not considerable.", 1),
    "smell": ("NOUN", "An odor or scent; also the sense by which odors are perceived through the nose.", 1),
    "smooth": ("ADJECTIVE", "Having an even surface without bumps, ridges, or irregularities.", 2),
    "society": ("NOUN", "A community of people living together bound by shared interests, culture, or institutions.", 1),
    "soft": ("ADJECTIVE", "Not hard or firm; easily yielding to pressure or touch.", 1),
    "softer": ("ADJECTIVE", "More soft; less firm or hard than something else.", 1),
    "soil": ("NOUN", "The upper layer of earth containing organic matter and supporting plant life; ground.", 1),
    "solid": ("ADJECTIVE", "Firm and stable; not liquid or gas; of dense consistency.", 3),
    "solidus": ("NOUN", "The forward slash (/) used in writing to separate alternatives or indicate division.", 2),
    "solution": ("NOUN", "The action of solving a problem or finding an answer to a question.", 2),
    "somewhat": ("ADVERB", "To some extent; rather; fairly; moderately.", 1),
    "sorrow": ("NOUN", "Deep sadness or grief, often caused by loss or disappointment.", 1),
    "sort": ("NOUN", "A type, kind, or category of person or thing.", 1),
    "south": ("NOUN", "The cardinal direction opposite north; the direction to the right when facing east.", 1),
    "special": ("ADJECTIVE", "Of a particular or specific kind; distinguished by some distinctive feature or quality.", 4),
    "species": ("NOUN", "A group of organisms capable of interbreeding and producing fertile offspring; a taxonomic rank.", 2),
    "specifically": ("ADVERB", "In a way that is precise, exact, or clearly defined; with particular reference.", 2),
    "spectators": ("NOUN", "People who watch a show, game, event, or other spectacle.", 1),
    "spends": ("VERB", "Uses money to purchase something; passes or uses time in an activity.", 1),
    "sperm": ("NOUN", "A male reproductive cell capable of fertilizing an ovum.", 1),
    "sphere": ("NOUN", "A particular area of activity, influence, or knowledge; domain or field.", 2),
    "spiral": ("NOUN", "A curve winding around a center point while gradually moving toward or away from it.", 1),
    "spread": ("VERB", "To extend or scatter over a wide area; to distribute or disseminate.", 1),
    "spun": ("VERB", "Past tense of spin; twisted fibers into thread or yarn.", 1),
    "square": ("NOUN", "A pair of angled punctuation marks used to enclose text.", 4),
    "staff": ("NOUN", "The employees of an organization or establishment; a body of assistants.", 1),
    "statistics": ("NOUN", "Numerical data; facts and figures collected for analysis and interpretation.", 1),
    "stimuli": ("NOUN", "Things that provoke or elicit a response, reaction, or physiological change.", 1),
    "storm": ("NOUN", "A violent disturbance of the atmosphere with strong wind and usually rain or snow; turmoil.", 1),
    "straightforward": ("ADJECTIVE", "Direct and uncomplicated; honest and frank; easy to understand.", 1),
    "strengthen": ("VERB", "To make or become strong or stronger; to reinforce.", 1),
    "strengthens": ("VERB", "Makes strong or stronger; reinforces or increases in intensity.", 1),
    "stretches": ("VERB", "Extends over a distance or area; makes longer or wider.", 1),
    "stretching": ("VERB", "The act of extending or making longer; becoming extended.", 1),
    "strive": ("VERB", "To make great effort; to try hard to achieve something.", 1),
    "striving": ("VERB", "Making great effort; trying hard to accomplish or achieve something.", 1),
    "strongly": ("ADVERB", "In a forceful, vigorous, or intense manner.", 2),
    "subjected": ("VERB", "Caused to undergo or experience something; exposed to.", 1),
    "succeeded": ("VERB", "Accomplished a goal or objective; came after in time or sequence.", 1),
    "success": ("NOUN", "The accomplishment of an intended goal or purpose; favorable outcome.", 2),
    "successive": ("ADJECTIVE", "Following one after another in uninterrupted sequence; consecutive.", 1),
    "suffering": ("NOUN", "Physical or mental pain; the state of undergoing pain or hardship.", 1),
    "sufficiently": ("ADVERB", "Adequately; to a sufficient degree; enough to satisfy a need.", 1),
    "sun": ("NOUN", "The star at the center of the solar system that provides light and heat to Earth.", 2),
    "superiority": ("NOUN", "The state or quality of being superior; higher rank or status than others.", 1),
    "surround": ("VERB", "To extend on all sides of something; to encircle or enclose.", 2),
    "surrounding": ("ADJECTIVE", "Located on all sides; enclosing or encompassing something.", 2),
    "surrounds": ("VERB", "Encircles or encloses completely; is all around something.", 1),
    "sustained": ("ADJECTIVE", "Maintained over a long period; prolonged; kept going without stopping.", 1),
    "symbolic": ("ADJECTIVE", "Representing something by means of symbols; emblematic or indicative.", 2),
    "sympathetic": ("ADJECTIVE", "Showing sympathy and understanding toward others; caring and compassionate.", 1),
    "talk": ("VERB", "To communicate or exchange ideas by speaking; to discuss.", 2),
    "talked": ("VERB", "Spoke; communicated or discussed with others in speech.", 1),
    "talking": ("VERB", "Speaking; communicating or conversing with others.", 1),
    "tangible": ("ADJECTIVE", "Able to be touched or felt; real and concrete rather than abstract.", 2),
    "taste": ("NOUN", "The sense by which flavor is perceived through the mouth; a small sample of food or drink.", 1),
    "teeth": ("NOUN", "Hard structures in the mouth used for biting and chewing; plural of tooth.", 1),
    "television": ("NOUN", "A medium for broadcasting visual and audio content; a device for receiving television broadcasts.", 1),
    "tendency": ("NOUN", "An inclination or likelihood to behave or act in a certain way; a leaning.", 1),
    "tending": ("VERB", "Caring for or managing; having a tendency toward; serving or working at.", 1),
    "tends": ("VERB", "Has a tendency or inclination; cares for; manages or serves at.", 1),
    "terms": ("NOUN", "Words or phrases used to express a concept or idea; conditions of an agreement.", 2),
    "territory": ("NOUN", "An area of land; a region or domain under control or belonging to a particular entity.", 1),
    "text": ("NOUN", "A piece of writing or printed matter; the main body of a book or document.", 3),
    "themes": ("NOUN", "Main subjects or ideas discussed or examined; recurring elements or motifs.", 1),
    "theoretical": ("ADJECTIVE", "Based on theory rather than practical experience; abstract; existing in theory only.", 1),
    "theory": ("NOUN", "A system of ideas intended to explain something; a hypothesis based on limited evidence.", 1),
    "thick": ("ADJECTIVE", "Large in extent from one surface to the opposite; not thin; densely packed.", 1),
    "thin": ("ADJECTIVE", "Having little thickness or depth; narrow or slender.", 3),
    "think": ("VERB", "To form ideas, opinions, or judgments in the mind; to use reason.", 2),
    "thinking": ("NOUN", "The process of using the mind to consider or reason about something.", 4),
    "thorough": ("ADJECTIVE", "Showing careful attention to detail; complete and comprehensive.", 1),
    "tool": ("NOUN", "An implement or device used to perform work or accomplish a task.", 1),
    "tools": ("NOUN", "Implements or devices used to perform work; instruments or equipment.", 1),
    "totally": ("ADVERB", "Completely; wholly; to the fullest extent.", 1),
    "totals": ("NOUN", "Complete sums or amounts; the final count or aggregate.", 1),
    "trace": ("NOUN", "A mark, sign, or evidence of something; a barely perceptible amount.", 1),
    "tract": ("NOUN", "A connected series of body parts or systems; an area or region of land.", 2),
    "trade": ("NOUN", "Commerce; the business of buying and selling goods; an occupation or craft.", 1),
    "trained": ("ADJECTIVE", "Having received instruction or practice in a skill; instructed and disciplined.", 1),
    "training": ("NOUN", "The process of teaching or learning a skill, behavior, or body of knowledge.", 2),
    "transfer": ("VERB", "To move or convey from one place, person, or thing to another.", 1),
    "transferred": ("VERB", "Moved or conveyed from one place, person, or thing to another.", 1),
    "transferring": ("VERB", "Moving or conveying from one place, person, or thing to another.", 1),
    "transition": ("NOUN", "A passage from one state, stage, condition, or place to another; a change.", 1),
    "transmitted": ("VERB", "Sent or conveyed; passed on information, signals, or disease.", 1),
    "transport": ("VERB", "To carry or convey from one place to another; to transfer.", 1),
    "transported": ("VERB", "Carried or conveyed from one place to another.", 1),
    "transporting": ("VERB", "Moving or conveying something from one place to another.", 2),
    "treat": ("VERB", "To behave toward or deal with; to provide medical care to; to entertain with food or refreshment.", 1),
    "treated": ("VERB", "Behaved toward or dealt with; provided medical care to; entertained with food or refreshment.", 1),
    "treating": ("VERB", "Behaving toward or dealing with; providing medical care to; entertaining with refreshment.", 1),
    "triangular": ("ADJECTIVE", "Having three angles and three sides; three-cornered; shaped like a triangle.", 1),
    "trust": ("NOUN", "Confidence in the reliability, ability, or honesty of someone or something.", 2),
    "tube": ("NOUN", "A long, hollow cylinder used for containing or conveying something; a pipe or duct.", 1),
    "typical": ("ADJECTIVE", "Characteristic of or conforming to an established type or standard.", 5),
    "unacceptable": ("ADJECTIVE", "Not worthy of being accepted; not allowed or approved; unsuitable.", 1),
    "unambiguous": ("ADJECTIVE", "Clear and having only one possible interpretation; not ambiguous or uncertain.", 2),
    "unavoidable": ("ADJECTIVE", "Cannot be avoided or prevented; inevitable; bound to happen.", 1),
    "uncertainty": ("NOUN", "The quality of being uncertain; doubt; lack of certainty or clear knowledge.", 1),
    "underlying": ("ADJECTIVE", "Lying beneath the surface; forming the basis or foundation of something.", 2),
    "understand": ("VERB", "To grasp the meaning, nature, or explanation of something.", 6),
    "understood": ("ADJECTIVE", "Comprehended or grasped mentally; accepted as known without being explicitly stated.", 3),
    "undertaken": ("VERB", "Agreed to do or undertake; began or started; committed oneself to.", 1),
    "undesirable": ("ADJECTIVE", "Not wanted or desired; unwelcome; objectionable or unpleasant.", 1),
    "undetermined": ("ADJECTIVE", "Not determined or decided; unspecified; left uncertain or unsettled.", 1),
    "unexpected": ("ADJECTIVE", "Not expected or anticipated; surprising.", 3),
    "unexpectedly": ("ADVERB", "In a manner not anticipated or foreseen; by surprise.", 4),
    "unfair": ("ADJECTIVE", "Not fair or just; unjust; treating people unequally or dishonestly.", 1),
    "uniform": ("ADJECTIVE", "Consistent or the same throughout; not varying in appearance or character.", 2),
    "unimportant": ("ADJECTIVE", "Not important; insignificant; trivial; of little consequence or value.", 1),
    "union": ("NOUN", "The joining or combining of entities; a political or economic organization of states or peoples.", 2),
    "uniquely": ("ADVERB", "In a way that is unlike anything else; in a manner that is distinctive or singular.", 2),
    "united": ("ADJECTIVE", "Joined together with a common purpose or feeling.", 4),
    "unmistakably": ("ADVERB", "In a way that cannot be mistaken or misunderstood; clearly; evidently.", 1),
    "unoccupied": ("ADJECTIVE", "Not occupied; empty; vacant; not inhabited or in use.", 1),
    "unpleasant": ("ADJECTIVE", "Not pleasant; disagreeable; displeasing; offensive to the senses or mind.", 1),
    "unsuccessful": ("ADJECTIVE", "Not successful; failing to achieve the desired outcome or goal.", 1),
    "untrue": ("ADJECTIVE", "Not true; false; contrary to fact.", 1),
    "unusual": ("ADJECTIVE", "Not usual; uncommon; rare; strange or out of the ordinary.", 1),
    "unwanted": ("ADJECTIVE", "Not wanted or desired; undesired; rejected or unnecessary.", 1),
    "unyielding": ("ADJECTIVE", "Not bending or giving way; firm; rigid; stubbornly refusing to change.", 1),
    "usage": ("NOUN", "The manner or frequency of using something; customary practice or common use.", 1),
    "useful": ("ADJECTIVE", "Able to be used for a practical purpose; producing desired results or benefits.", 2),
    "usefulness": ("NOUN", "The quality of being useful; utility; practical value or benefit.", 1),
    "utter": ("VERB", "To speak; to say or express in words.", 1),
    "uttered": ("VERB", "Spoken aloud or produced as vocal sound from the mouth.", 2),
    "valid": ("ADJECTIVE", "Well-grounded or justifiable; having legal or logical force.", 4),
    "validity": ("NOUN", "The quality of being logically or factually sound, correct, or legally binding.", 2),
    "valued": ("ADJECTIVE", "Regarded as important or precious; esteemed; considered worthy.", 1),
    "versions": ("NOUN", "Particular forms, variants, or adaptations of something; different accounts or renderings.", 1),
    "vertebrates": ("NOUN", "Animals with a backbone or spinal column; creatures having an internal skeleton.", 1),
    "vessel": ("NOUN", "A container used to hold or transport liquids or other materials; a ship or boat.", 1),
    "victory": ("NOUN", "Success in a contest, battle, or struggle; triumph; winning.", 1),
    "view": ("NOUN", "A way of understanding, regarding, or thinking about something; a perspective or opinion.", 3),
    "viewed": ("VERB", "Looked at; regarded or considered; watched or examined.", 1),
    "violent": ("ADJECTIVE", "Involving or characterized by force, severity, or physical force intended to hurt; intense.", 1),
    "visual": ("ADJECTIVE", "Relating to sight or the eyes; able to be seen or perceived.", 2),
    "vitality": ("NOUN", "Physical strength and liveliness; energy; the quality of being alive and vigorous.", 1),
    "voluntarily": ("ADVERB", "Done by one's own choice or free will; not forced or compelled.", 2),
    "wagons": ("NOUN", "Four-wheeled vehicles for carrying goods or passengers; carts or conveyances.", 1),
    "wait": ("VERB", "To stay in a place or remain inactive until something happens; to delay action.", 1),
    "waiting": ("VERB", "Staying in a place or remaining inactive until something happens; awaiting.", 1),
    "walks": ("VERB", "Moves on foot; travels by putting one foot in front of the other.", 1),
    "wall": ("NOUN", "A vertical structure of stone, brick, or other material; a barrier or boundary.", 1),
    "warm": ("ADJECTIVE", "Having or giving off heat; having a temperature between cool and hot.", 1),
    "warmly": ("ADVERB", "In a manner showing genuine affection, friendliness, or enthusiasm.", 2),
    "warning": ("NOUN", "A notice or indication of danger, risk, or a forthcoming event; a cautionary sign.", 1),
    "wavering": ("ADJECTIVE", "Showing doubt or hesitation; unsteady; fluctuating or changing.", 1),
    "weaving": ("NOUN", "The act or process of creating fabric by interlacing threads or strands.", 2),
    "wheels": ("NOUN", "Circular objects that rotate on an axle; used on vehicles for movement.", 1),
    "white": ("ADJECTIVE", "Of the color produced by mixing all visible light wavelengths; the lightest color.", 3),
    "wide": ("ADJECTIVE", "Great in extent from one side to the other; broad or spacious.", 2),
    "willingly": ("ADVERB", "Done with readiness or eagerness; without reluctance or opposition.", 2),
    "win": ("VERB", "To be victorious in a contest or competition; to achieve success or gain something.", 1),
    "wise": ("ADJECTIVE", "Having wisdom; showing good judgment and sensibility; prudent.", 1),
    "wish": ("VERB", "To want or desire; to express a hope or longing for something.", 1),
    "wished": ("VERB", "Wanted or desired; expressed a hope or longing for something.", 1),
    "wishes": ("NOUN", "Desires or hopes for something to happen or to be true.", 3),
    "withstand": ("VERB", "To resist or bear up against; to endure without giving way.", 1),
    "wood": ("NOUN", "The hard material forming the trunk and branches of trees; timber.", 1),
    "working": ("ADJECTIVE", "Engaged in work or labor; functioning or operating properly.", 4),
    "works": ("NOUN", "Creations or compositions, especially of literature or art; the functional parts of a machine or device.", 2),
    "worry": ("VERB", "To feel anxious or troubled about something; to cause anxiety to.", 1),
    "worthy": ("ADJECTIVE", "Deserving or having worth or merit; commendable; suitable or adequate.", 1),
    "wound": ("VERB", "Past tense of wind; twisted or coiled around an axis or center.", 1),
    "writer": ("NOUN", "A person who writes; an author of books, articles, or other written works.", 1),
    "wrongdoing": ("NOUN", "Unethical or illegal action; misconduct; morally reprehensible behavior.", 1),
    "year": ("NOUN", "A period of approximately 365 days marking one complete orbit of Earth around the sun.", 2),
}
