"""One-time migration: backfills a stable `entry_id` into every entry of
every Common Vocabulary Cache word file (WordSeeder.MANDATORY_FILES,
SUPPLEMENTARY_FILES, and promoted_words.json) -- the persistent
Qualified Word Identity Word.entry_id's own docstring describes, added
so a UI (or anything else) can tell two distinct (domain, part_of_speech,
lexical_form) vocabulary entries apart without needing to mangle
lexical_form into something like "particle_2" to do it (that mechanism,
DictionaryProcessor.register_conflicting_sense, is fixed separately to
rely on entry_id instead -- see examples/README.md).

entry_id is generated once, here, and written directly into each JSON
entry, as the first key (before lexical_form) to signal it's the
primary identity field -- every other key keeps its existing order.
Idempotent: an entry that already has a non-empty entry_id is left
untouched, so re-running this script after it's already been applied
is a no-op. Only touches the Common Vocabulary Cache's own word files --
Physics Domain words (hydrated at runtime from fixture data standing in
for an external API, examples/physics_domain_seeding_fixtures.py) get
their entry_id the same way they already get their uuid: freshly
generated by Word's own default_factory at construction time, since
they were never loaded from a stored cache entry in the first place.

Run from the repository root:

    python3 examples/word_entry_id_backfill.py
"""

import json
import uuid
from pathlib import Path

ASSETS_DIR = Path(__file__).resolve().parent.parent / "src" / "lira" / "vocabulary" / "assets" / "common" / "en"

WORD_FILES = (
    "determiners.json",
    "pronouns.json",
    "auxiliaries.json",
    "prepositions.json",
    "coordinating_conjunctions.json",
    "subordinating_conjunctions.json",
    "particles.json",
    "punctuation.json",
    "symbols.json",
    "numerals.json",
    "metalinguistic_nouns.json",
    "metalinguistic_verbs.json",
    "metalinguistic_adjectives.json",
    "metalinguistic_adverbs.json",
    "metalinguistic_proper_nouns.json",
    "metalinguistic_interjections.json",
    "promoted_words.json",
)


def _load_json(filename: str) -> dict:
    return json.loads((ASSETS_DIR / filename).read_text())


def _save_json(filename: str, doc: dict) -> None:
    (ASSETS_DIR / filename).write_text(json.dumps(doc, indent=2, ensure_ascii=False) + "\n")


def _backfill_entry(entry: dict) -> dict:
    if entry.get("entry_id"):
        return entry
    return {"entry_id": str(uuid.uuid4()), **entry}


def run() -> dict:
    report = {}
    for filename in WORD_FILES:
        doc = _load_json(filename)
        before = sum(1 for entry in doc["words"] if entry.get("entry_id"))
        doc["words"] = [_backfill_entry(entry) for entry in doc["words"]]
        after = sum(1 for entry in doc["words"] if entry.get("entry_id"))
        added = after - before
        if added:
            _save_json(filename, doc)
        report[filename] = {"total": len(doc["words"]), "already_had_entry_id": before, "added": added}
    return report


if __name__ == "__main__":
    result = run()
    total_added = sum(r["added"] for r in result.values())
    total_words = sum(r["total"] for r in result.values())
    for filename, r in result.items():
        print(f"{filename}: {r['total']} entries, {r['added']} entry_id added, {r['already_had_entry_id']} already had one")
    print(f"\nTotal: {total_words} entries, {total_added} entry_id backfilled")
